export const homeAbout = [
  {
    id: 1,
    cover: "https://img.icons8.com/dotty/80/000000/storytelling.png",
    title: "Online Courses",
    desc: "far far away, behind the word mountains, far from the countries India, there live the blind texts",
  },
  {
    id: 1,
    cover: "https://img.icons8.com/ios/80/000000/diploma.png",
    title: "Earn a Certificates",
    desc: "far far away, behind the word mountains, far from the countries India, there live the blind texts",
  },
  {
    id: 1,
    cover: "https://img.icons8.com/ios/80/000000/athlete.png",
    title: "Learn with Expert",
    desc: "far far away, behind the word mountains, far from the countries India, there live the blind texts",
  },
];

export const awrapper = [
  {
    cover:
      "https://img.icons8.com/external-yogi-aprelliyanto-basic-outline-yogi-aprelliyanto/80/ffffff/external-graduation-education-yogi-aprelliyanto-basic-outline-yogi-aprelliyanto.png",
    data: "300",
    title: "SUCCESS STORIES",
  },
  {
    cover: "https://img.icons8.com/ios/80/ffffff/image.png",
    data: "100",
    title: "PROJECTS",
  },
];
export const jobsCard = [
  // {
  //   id: 1,
  //   Name: "Motorola Solutions ",
  //   Location: "Bangalore",
  //   Qualification: " Bachelor’s/ Master’s/ Doctoral Degree",
  //   Batch: "2019/ 2020/ 2021/ 2022/ 2023/ 2024",
  //   Salary: "Up to 8 LPA (Expected)",
  //   link: "https://motorolasolutions.wd5.myworkdayjobs.com/en-US/Careers/job/Bangalore-India/Internship-Trainee_R37615?",
  // },
  {
    id: 2,
    Name: "Nokia is hiring for Student Trainee ",
    Location: "Bangalore",
    Qualification: " Any Graduation",
    Batch: "2018/ 2019/ 2020/ 2021/ 2022/ 2023/ 2024",
    Salary: "Up to 30K Per Month (Expected)",
    link: "https://careers.nokia.com/jobs/student-trainee-99308",
  },
  {
    id: 3,
    Name: "NielsenIQ is hiring for Data Analyst ",
    Location: "Multiple",
    Qualification: " Any Graduation/ Diploma",
    Batch: "2018/ 2019/ 2020/ 2021/ 2022/ 2023",
    Salary: "Up to 6 LPA (Expected)",
    link: "https://jobs.smartrecruiters.com/NielsenIQ/743999907806443-data-processing-analyst",
  },
  // {
  //   id: 4,
  //   Name: "HPE is hiring for Systems Software Engineer ",
  //   Location: "Bangalore",
  //   Qualification: "  BE/ B.Tech/ ME/ M.Tech",
  //   Batch: "2018/ 2019/ 2020/ 2021/ 2022/ 2023",
  //   Salary: "Up to 16 LPA (Expected)",
  //   link: "https://careers.hpe.com/us/en/job/HPE1US1150170EXTERNALENUS/Software-Engineer",
  // },
  {
    id: 5,
    Name: "Tech Mahindra is hiring for Customer Support Associate ",
    Location: "Work From Home",
    Qualification: " Any Graduation",
    Batch: "2018/ 2019/ 2020/ 2021/ 2022/ 2023",
    Salary: "Up to 3.4 LPA (Expected)",
    link: "https://www.naukri.com/job-listings-hiring-for-graduate-freshers-at-tech-mahindra-tech-mahindra-noida-ghaziabad-faridabad-greater-noida-delhi-ncr-0-to-5-years-200223003703?src=simjobsjd_rt",
  },
  {
    id: 6,
    Name: "Baker Hughes is hiring for Mechanical Engineer ",
    Location: "Bangalore",
    Qualification: " Any Graduation",
    Batch: "2019/ 2020/ 2021/ 2022/ 2023",
    Salary: "Up to 10 LPA (Expected)",
    link: "https://careers.bakerhughes.com/global/en/job/R82520/Mechanical-Design-Engineer",
  },
  {
    id: 7,
    Name: "Apple is hiring for Software Engineer ",
    Location: "Hyderabad/ Bengaluru",
    Qualification: " Any Graduation",
    Batch: "2019/ 2020/ 2021/ 2022/ 2023",
    Salary: "Up to 14 LPA (Expected)",
    link: "https://jobs.apple.com/en-us/details/200479641/system-software-engineer",
  },
  {
    id: 8,
    Name: "Thryve Digital is hiring for Trainee ",
    Location: "Hyderabad/ Chennai",
    Qualification: " Diploma/ Any UG/ PG",
    Batch: "2018/ 2019/ 2020/ 2021/ 2022/ 2023",
    Salary: "Up to 6 LPA (Expected)",
    link: "https://app339.workline.hr/CandidatePortal/979ed720-e149-4a5d-a436-4df6950c2257/Trainee-6860",
  },
  {
    id: 9,
    Name: "Deloitte is hiring for Associate Analyst ",
    Location: "Hyderabad",
    Qualification: " Any Graduation",
    Batch: "2017/ 2018/ 2019/ 2020/ 2021/ 2022/ 2023",
    Salary: "Up to 6 LPA (Expected)",
    link: "https://usijobs.deloitte.com/careersUSI/JobDetail/EH-EA-MF-AU-Client-Data-Management-Associate-Analyst/146160",
  },
  {
    id: 10,
    Name: "Cognizant is hiring for Devops Engineer ",
    Location: " Hyderabad",
    Qualification: "BE/ B.Tech/ B.Sc/ ME/ M.Tech",
    Batch: "2017/ 2018/ 2019/ 2020/ 2021/ 2022/ 2023",
    Salary: "Up to 6.8 LPA (Expected)",
    link: "https://careers.cognizant.com/global/en/job/00053706419/DevOps-Engineer-Associate",
  },
];

export const blog = [
  {
    id: 1,
    type: "admin",
    date: "JAN. 18, 2021",
    com: "3 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b1.webp",
  },
  {
    id: 2,
    type: "admin",
    date: "API. 25, 2022",
    com: "5 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b2.webp",
  },
  {
    id: 3,
    type: "user",
    date: "MAY. 15, 2022",
    com: "10 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b3.webp",
  },
  {
    id: 4,
    type: "admin",
    date: "JAN. 02, 2022",
    com: "3 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b4.webp",
  },
  {
    id: 5,
    type: "admin",
    date: "DEC. 14, 2022",
    com: "3 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b5.webp",
  },
  {
    id: 6,
    type: "user",
    date: "JAN. 18, 2021",
    com: "12 COMMENTS ",
    title: "Build your Dream Software & Engineering Career",
    desc: "A small river named Duden flows by their place and supplies it with the necessary regelialia.",
    cover: "../images/blog/b6.webp",
  },
];
